#!/bin/bash

SESSIONNAME="work"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ]
	then
		tmux new -s $SESSIONNAME -d
    tmux split-window -h
    tmux set-option -w synchronize-panes
    tmux send-keys -t $SESSIONNAME "cd /home/nbenevento/Documents/blackcape" Enter
    tmux send-keys "clear" Enter
    tmux set-option -w synchronize-panes

		
fi

tmux attach-session -t $SESSIONNAME

